<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-SDVCEDF4" failures="1" tests="5" name="com.api.auto.testcase.TC_API_Login" time="2.080" errors="0" timestamp="2023-02-24T20:09:42 ICT" skipped="0">
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC01_Validate200Ok" time="0.023"/>
  <system-out/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC02_ValidateMessage" time="1.890"/>
  <system-out/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC03_ValidateToken" time="0.060"/>
  <system-out/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC05_ValidateUserType" time="0.042"/>
  <system-out/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC06_ValidateAccount" time="0.065">
    <failure message="trường password không khớp với password đăng nhặp expected [Abc13579hjk] but found [Abc13579]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: trường password không khớp với password đăng nhặp expected [Abc13579hjk] but found [Abc13579]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.api.auto.testcase.TC_API_Login.TC06_ValidateAccount(TC_API_Login.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC06_ValidateAccount -->
  <system-out/>
</testsuite> <!-- com.api.auto.testcase.TC_API_Login -->
